services:
  - type: web
    name: together-ai-image-api
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: TOGETHER_API_KEY
        sync: false
      - key: TOGETHER_API_URL
        value: https://api.together.xyz
    healthCheckPath: /api/health 