name: Deploy to Render via Webhook

on:
  push:
    branches:
      - main  # 或者用你的主分支名称，如master
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to Render through webhook
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
        
      - name: Verify deployment status
        run: |
          echo "已触发Render部署"
          echo "请前往Render控制台查看部署状态" 